### ISSUE TITLE
Immersive Portal Root Shell Bug?

### ISSUE THREAD

**Issue by EchogeTheFurry77** [Suff99/TardisRefined#163] opened 2023-07-25 19:59 UTC
### Issue description

With Immersive Portals mod installed with TARDIS Refined, The Root shell doesn't render the portal and when entering or exiting root shell before terraform it doesnt load terrain and have to Alt+f4 the game to then reload the save. This sort if fixes it but have to do that every single time when entering. Sometimes when trying to terraform the interior the process does not begin when using the correct blocks (one redstone block surrounded by 8 copper blocks in a 9x9 fashion, terraformer final bloc on top)

### Steps to reproduce

1. Enter TARDIS (if doesn't load Alt+F4)
2. When inside Shell Interior, Create multiblock structure for terraforming
3. Try Exiting

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

43.2.8

### Tardis Refined version

v1.0

**Comment by 50ap5ud5** [comment] 2023-07-25 22:57
Hi, it is intentional that the Root Shell doesn't show a portal with Immersive Portals. Before you enter the Tardis dimension doesn't exist yet so a portal cannot be added. After the dimension is generated we still do some generation work inside the dimension so currently it isn't worth adding workarounds and special cases just for the portal.

There is a known issue with Immersive Portals on Forge causing data loss which can be related to the issues you experience. See #148. 

The terraformer not activating could be related to compatibility issues caused by other mods. If you only use Tardis Refined on its own, can you reproduce this issue?

Hope this helps.

**Comment by Suff99** [comment] 2023-08-06 14:24
Closing due to being a duplicate, if there is further comments that advocate for a re-opening, the issue will be opened again

**Closed by Suff99** 2023-08-06 14:24 UTC
Labels: duplicate, data issue, compatibility issue, forge
