### ISSUE TITLE
[1.20.2 Development Build] Adding Console Patterns only works in tardis_refined namespace

### ISSUE THREAD

**Issue by dhi-holo** [Suff99/TardisRefined#186] opened 2023-12-17 04:25 UTC
### Issue description

When attempting to test making a new console skin, I used the namespace `tt_holo`, just so it wouldn't be the default namespace, and it would be customised for myself. However, even with the json written below, it wasn't showing up in game. However, when I changed the datapack namespace to `tardis_refined`, it showed up immediately on `/reload`.
This is not the intended behaviour, according to [the wiki page.](https://github.com/Suff99/TardisRefined/wiki/5.-Datapack-Customisation#datapack-1)

The exact datapack file paths are:
`TT Holo [Datapack]\data\tt_holo\tardis_refined\patterns\console\toyota.json`
`TT Holo [Datapack]\data\tardis_refined\tardis_refined\patterns\console\toyota.json`
The second one functions, the first does not. No other changes were made to the pack.

The json is
``` json
{
  "patterns": [
    {
      "id": "tt_holo:wood",
      "name_component": "{\"color\":\"yellow\",\"text\":\"Wood\"}",
      "texture_definition": {
        "emissive": true,
        "texture": "tt_holo:textures/textures/blockentity/console/toyota/toyota_console_wood.png"
      }
    }
  ]
}
```

### Steps to reproduce

1) Make a datapack which attempts to add new patterns to a console in a random valid namespace (such as `tt_holo`)
2) Check if pattern exists in-game (the result should be that it does appear in-game)
3) Change used namespace to `tardis_refined`
4) Check if pattern exists in-game (the result here should always be that it does appear)

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.15.1 (1.20.2)

### Tardis Refined version

v1.0.1

### Other relevant versions

1.20.2 Development Build, do not trust the Minecraft version field.

**Comment by 50ap5ud5** [comment] 2023-12-17 09:46
Thanks for pointing this out dhi. The behaviour you described is now intended behaviour as of the 1.20 development. As part of #182 we changed pattern merging behaviour to act like vanilla tags, where all json file entries with the same namespace will be merged. 

The previous behaviour where any namespace was allowed was misleading, because in the back end we would hardcode it to `tardis_refined`, meaning if you wanted to add a console pattern or shell pattern for a console/shell added by an addon mod, it would not be possible to do so.

The documentation on the wiki is user facing, intended only for publicly released builds. We will update the documentation in due time when the 1.20 version is released. :)

**Closed by 50ap5ud5** 2023-12-17 09:46 UTC

**Comment by dhi-holo** [comment] 2023-12-17 09:49
I didn't realise that had changed, hadn't really messed with this content in 1.19 so I was going off what I could see in the change history, and I didn't notice anything implying that the wiki would be totally outdated on that front.
Thanks for the heads up
