### ISSUE TITLE
Terraformer not working

### ISSUE THREAD

**Issue by ziolkoplays** [Suff99/TardisRefined#166] opened 2023-10-17 02:29 UTC
### Issue description

when i place the teraformer inside the tardis, it doesn't work
![2023-10-16_21 24 50](https://github.com/Suff99/TardisRefined/assets/124638625/e49ec991-06fc-4e16-9cf8-37dab514e270)

### Steps to reproduce

1.9x9 copper block platform with redstone block replacing the center
2.terraformer on top of redstone
3.DOSENT WORK!!!

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Forge - 43.3.0

### Tardis Refined version

v1.0

### Other relevant versions

immersive-portals-2.3.5-mc1.19.2-forge

**Comment by 50ap5ud5** [comment] 2023-10-17 07:13
Duplicate of #148, unfortunately the Forge version of Immersive Portals causes this compatibility issue. You can work around this issue but placing down a console, then selecting a Desktop in the Computer Bank GUI.

**Closed** 2023-10-18 08:57 UTC
Labels: duplicate, compatibility issue
